version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: historylens-backend
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./backend/outputs:/app/outputs
      - ./backend/sample_data:/app/sample_data
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: historylens-frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
